server:
  port: 8076
  forward-headers-strategy: framework
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-kafka-samples
  kafka:
    bootstrap-servers: localhost:9092
    bindings:
      customer:
        topic: "customer"
        group: "customer-group"
    retries:
      customer:
        maxRetryAttempts: 3
        exponentialBackoffMultiplier: 2
        waitDuration: 5000
        autoCreateTopics: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  name: ${spring.application.name}
  description: Circuit Breaker Demo
  environment: ${spring.profiles.active}
  version: 0.0.1

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  cache:
    disabled: true

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    io.github.susimsek.springkafkasamples: DEBUG